name: drlnd-p1-navigation
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - decorator=4.4.1=py_0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.12.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.16.0=py36_0
  - jupyter_client=5.3.4=py36_0
  - jupyter_core=4.6.1=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libsodium=1.0.16=h3efe00b_0
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.0.2=py36_1
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.5.2=py_0
  - python=3.6.10=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - setuptools=45.2.0=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py36h1de35cc_3
  - traitlets=4.3.3=py36_0
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.9.0
    - alembic==1.4.0
    - astor==0.8.1
    - attrs==19.3.0
    - autopep8==1.5
    - bleach==1.5.0
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.3.0
    - colorcet==2.0.2
    - configparser==4.0.2
    - cycler==0.10.0
    - databricks-cli==0.9.1
    - defusedxml==0.6.0
    - docker==4.2.0
    - docopt==0.6.2
    - entrypoints==0.3
    - flake8==3.7.9
    - flask==1.1.1
    - gast==0.3.3
    - gitdb==4.0.2
    - gitpython==3.1.0
    - gorilla==0.3.0
    - grpcio==1.11.0
    - gunicorn==20.0.4
    - html5lib==0.9999999
    - idna==2.9
    - importlib-metadata==1.5.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jinja2==2.11.1
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-console==6.1.0
    - kiwisolver==1.1.0
    - mako==1.1.1
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mlflow==1.6.0
    - more-itertools==8.2.0
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - notebook==6.0.3
    - numpy==1.18.1
    - packaging==20.1
    - pandas==1.0.1
    - pandocfilters==1.4.2
    - param==1.9.3
    - pillow==7.0.0
    - plotly==4.5.4
    - pluggy==0.13.1
    - prometheus-client==0.7.1
    - prometheus-flask-exporter==0.12.2
    - protobuf==3.11.3
    - py==1.8.1
    - pycodestyle==2.5.0
    - pyct==0.4.6
    - pyflakes==2.1.1
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - pytest==5.3.5
    - python-editor==1.0.4
    - pytz==2019.3
    - pyyaml==5.3
    - qtconsole==4.6.0
    - querystring-parser==1.2.4
    - requests==2.23.0
    - retrying==1.3.3
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.10.0
    - send2trash==1.5.0
    - simplejson==3.17.0
    - smmap==3.0.1
    - sqlalchemy==1.3.13
    - sqlparse==0.3.0
    - tabulate==0.8.6
    - tensorboard==1.7.0
    - tensorflow==1.7.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.4.0
    - unityagents==0.4.0
    - urllib3==1.25.8
    - websocket-client==0.57.0
    - werkzeug==1.0.0
    - widgetsnbextension==3.5.1
    - zipp==3.0.0


